version: "3"
services:
  app:
    container_name: bot
    build: .
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
      SSL_MODE: false
      DISCORD_SECRET: ${DISCORD_SECRET}
      GUILD_IDS: ${GUILD_IDS}
    depends_on: 
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
